blank_issues_enabled: false
contact_links:
  - name: â“Â¿TenÃ©s alguna consulta para hacernos?
    url: https://discord.com/channels/594363964499165194/1109220285841944586
    about: PodÃ©s compartirla en el canal "ğŸš | la-cuentoneta" del Discord de FrontendCafÃ©.
